---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_redhat7_sat: []

foreman_products_redhat7_sat:
  - name: Red Hat Satellite
    organization: "{{ foreman_organization_redhat7_sat }}"
    repository_sets:
      # Red Hat Satellite 6.10 for RHEL 7 Server RPMs x86_64
      - name: Red Hat Satellite 6.10 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
        label: rhel-7-server-satellite-6.10-rpms
        organization: "{{ foreman_organization_redhat7_sat }}"
      # Red Hat Satellite 6.11 for RHEL 7 Server RPMs x86_64
      - name: Red Hat Satellite 6.11 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
        label: rhel-7-server-satellite-6.11-rpms
        organization: "{{ foreman_organization_redhat7_sat }}"

  - name: Red Hat Satellite Capsule
    organization: "{{ foreman_organization_redhat7_sat }}"
    repository_sets:
      # Red Hat Satellite Capsule 6.10 for RHEL 7 Server RPMs x86_64
      - name: Red Hat Satellite Capsule 6.10 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
        label: rhel-7-server-satellite-capsule-6.10-rpms
        organization: "{{ foreman_organization_redhat7_sat }}"
      # Red Hat Satellite Capsule 6.11 for RHEL 7 Server RPMs x86_64
      - name: Red Hat Satellite Capsule 6.11 (for RHEL 7 Server) (RPMs)
        basearch: x86_64
        label: rhel-7-server-satellite-capsule-6.11-rpms
        organization: "{{ foreman_organization_redhat7_sat }}"

foreman_content_views_redhat7_sat:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_610"
    organization: "{{ foreman_organization_redhat7_sat }}"
    repositories:
      - name: Red Hat Satellite 6.10 for RHEL 7 Server RPMs x86_64
        product: Red Hat Satellite
    allow_promote: "{{ foreman_cv_allow_promote_redhat7_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_611"
    organization: "{{ foreman_organization_redhat7_sat }}"
    repositories:
      - name: Red Hat Satellite 6.11 for RHEL 7 Server RPMs x86_64
        product: Red Hat Satellite
    allow_promote: "{{ foreman_cv_allow_promote_redhat7_sat }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_capsule_610"
    organization: "{{ foreman_organization_redhat7_sat }}"
    repositories:
      - name: Red Hat Satellite Capsule 6.10 for RHEL 7 Server RPMs x86_64
        product: Red Hat Satellite Capsule
    allow_promote: "{{ foreman_cv_allow_promote_redhat7_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_capsule_611"
    organization: "{{ foreman_organization_redhat7_sat }}"
    repositories:
      - name: Red Hat Satellite Capsule 6.11 for RHEL 7 Server RPMs x86_64
        product: Red Hat Satellite Capsule
    allow_promote: "{{ foreman_cv_allow_promote_redhat7_sat }}"

foreman_composite_content_views_redhat7_sat:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_satellite"
    organization: "{{ foreman_organization_redhat7_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat7_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat7_sat }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_base"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_optional"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_rhscl"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_2"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_29"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_610"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_611"
        latest: true

  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_capsule"
    organization: "{{ foreman_organization_redhat7_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat7_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat7_sat }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_base"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_optional"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_rhscl"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_2"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_29"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_capsule_610"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_satellite_capsule_611"
        latest: true

foreman_operatingsystems_redhat7_sat: []

foreman_installation_media_redhat7_sat: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to uyse a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el7: &foreman_activation_keys_defaults_el7
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Enterprise Linux Server"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 7Server

foreman_activation_keys_redhat7_sat:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel7_satellite"
    organization: "{{ foreman_organization_redhat7_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_satellite"
    <<: *foreman_activation_keys_defaults_el7
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux Server"
    #   - name: "Red Hat Satellite"
    #   - name: "Red Hat Software Collections (for RHEL Server)"
    content_overrides:
      - label: rhel-7-server-rpms
        override: default
      - label: rhel-7-server-extras-rpms
        override: default
      - label: rhel-7-server-optional-rpms
        override: default
      - label: rhel-7-server-supplementary-rpms
        override: default
      - label: rhel-server-rhscl-7-rpms
        override: default
      - label: rhel-7-server-ansible-2-rpms
        override: default
      - label: rhel-7-server-ansible-2.9-rpms
        override: default
      - label: rhel-7-server-satellite-6.10-rpms
        override: default
      - label: rhel-7-server-satellite-6.11-rpms
        override: default

  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel7_capsule"
    organization: "{{ foreman_organization_redhat7_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_capsule"
    <<: *foreman_activation_keys_defaults_el7
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux Server"
    #   - name: "Red Hat Satellite Capsule"
    #   - name: "Red Hat Software Collections (for RHEL Server)"
    content_overrides:
      - label: rhel-7-server-rpms
        override: default
      - label: rhel-7-server-extras-rpms
        override: default
      - label: rhel-7-server-optional-rpms
        override: default
      - label: rhel-7-server-supplementary-rpms
        override: default
      - label: rhel-server-rhscl-7-rpms
        override: default
      - label: rhel-7-server-ansible-2-rpms
        override: default
      - label: rhel-7-server-ansible-2.9-rpms
        override: default
      - label: rhel-7-server-satellite-capsule-6.10-rpms
        override: default
      - label: rhel-7-server-satellite-capsule-6.11-rpms
        override: default

foreman_sync_plan_products_redhat7_sat:
  - Red Hat Ansible Engine
  - Red Hat Enterprise Linux Server
  - Red Hat Satellite
  - Red Hat Satellite Capsule
  - Red Hat Software Collections (for RHEL Server)

