---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_redhat7_aap: []

foreman_products_redhat7_aap:
  - name: Red Hat Ansible Automation Platform
    organization: "{{ foreman_organization_redhat7_aap }}"
    repository_sets:
      # Red Hat Automation Hub 4.2 for RHEL 7 RPMs x86_64
      - name: Red Hat Automation Hub 4.2 for RHEL 7 (RPMs)
        basearch: x86_64
        label: rhel-7-server-automation-hub-4.2-rpms
        organization: "{{ foreman_organization_redhat7_aap }}"

foreman_content_views_redhat7_aap:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_automation_hub_42"
    organization: "{{ foreman_organization_redhat7_aap }}"
    repositories:
      - name: Red Hat Automation Hub 4.2 for RHEL 7 RPMs x86_64
        product: Red Hat Ansible Automation Platform
    allow_promote: "{{ foreman_cv_allow_promote_redhat7_aap }}"

foreman_composite_content_views_redhat7_aap:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_aap"
    organization: "{{ foreman_organization_redhat7_aap }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat7_aap }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat7_aap }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_base"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_extras"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_optional"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_sat_client_6"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_2"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_ansible_29"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel7_automation_hub_42"
        latest: true

foreman_operatingsystems_redhat7_aap: []

foreman_installation_media_redhat7_aap: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to uyse a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el7: &foreman_activation_keys_defaults_el7
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux Server"
  #   - name: "Red Hat Software Collections (for RHEL Server)"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 7Server

foreman_activation_keys_redhat7_aap:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel7_aap"
    organization: "{{ foreman_organization_redhat7_aap }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel7_aap"
    <<: *foreman_activation_keys_defaults_el7
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Ansible Automation Platform"
    #   - name: "Red Hat Enterprise Linux Server"
    content_overrides:
      - label: rhel-7-server-rpms
        override: default
      - label: rhel-7-server-extras-rpms
        override: default
      - label: rhel-7-server-optional-rpms
        override: default
      - label: rhel-7-server-supplementary-rpms
        override: default
      - label: rhel-7-server-satellite-client-6-rpms
        override: default
      - label: rhel-7-server-ansible-2-rpms
        override: default
      - label: rhel-7-server-ansible-2.9-rpms
        override: default
      - label: rhel-7-server-automation-hub-4.2-rpms
        override: default

foreman_sync_plan_products_redhat7_aap:
  - Red Hat Ansible Engine
  - Red Hat Ansible Automation Platform
  - Red Hat Enterprise Linux Server

