---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_redhat9_sat616: []

foreman_content_credentials_redhat9_sat_main: []
foreman_content_credentials_redhat9_sat: "{{ ( foreman_content_credentials_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_content_credentials_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_products_redhat9_sat616:
  - name: Red Hat Satellite
    organization: "{{ foreman_organization_redhat9_sat616 }}"
    repository_sets:
      # Red Hat Satellite 6.16 for RHEL 9 x86_64 RPMs
      - name: Red Hat Satellite 6.16 for RHEL 9 x86_64 (RPMs)
        basearch: x86_64
        label: satellite-6.16-for-rhel-9-x86_64-rpms
        organization: "{{ foreman_organization_redhat9_sat616 }}"

  - name: Red Hat Satellite Capsule
    organization: "{{ foreman_organization_redhat9_sat616 }}"
    repository_sets:
      # Red Hat Satellite Capsule 6.16 for RHEL 9 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.16 for RHEL 9 x86_64 (RPMs)
        basearch: x86_64
        label: satellite-capsule-6.16-for-rhel-9-x86_64-rpms
        organization: "{{ foreman_organization_redhat9_sat616 }}"

foreman_products_redhat9_sat_main: []
foreman_products_redhat9_sat: "{{ ( foreman_products_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_products_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_content_views_redhat9_sat616:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_satellite_616"
    organization: "{{ foreman_organization_redhat9_sat616 }}"
    repositories:
      - name: Red Hat Satellite 6.16 for RHEL 9 x86_64 RPMs
        product: Red Hat Satellite
    allow_promote: "{{ foreman_cv_allow_promote_redhat9_sat616 }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_satellite_capsule_616"
    organization: "{{ foreman_organization_redhat9_sat616 }}"
    repositories:
      - name: Red Hat Satellite Capsule 6.16 for RHEL 9 x86_64 RPMs
        product: Red Hat Satellite Capsule
    allow_promote: "{{ foreman_cv_allow_promote_redhat9_sat616 }}"

foreman_content_views_redhat9_sat_main: []
foreman_content_views_redhat9_sat: "{{ ( foreman_content_views_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_content_views_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_composite_content_views_redhat9_sat616: []

foreman_composite_content_views_redhat9_sat616_compents:
  - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_satellite_616"
    latest: true

foreman_composite_content_views_redhat9_sat616_capsule_compents:
  - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_satellite_capsule_616"
    latest: true

foreman_composite_content_views_redhat9_sat_main_compents:
  - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_baseos"
    latest: true
  - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_appstream"
    latest: true
  - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel9_supplementary"
    latest: true

foreman_composite_content_views_redhat9_sat_main:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9_satellite_616"
    organization: "{{ foreman_organization_redhat9_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat9_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat9_sat }}"
    components: "{{ ( foreman_composite_content_views_redhat9_sat_main_compents | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
      union( foreman_composite_content_views_redhat9_sat616_compents | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
    }}"

  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9_capsule_616"
    organization: "{{ foreman_organization_redhat9_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat9_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat9_sat }}"
    components: "{{ ( foreman_composite_content_views_redhat9_sat_main_compents | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
      union( foreman_composite_content_views_redhat9_sat616_capsule_compents | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
    }}"

foreman_composite_content_views_redhat9_sat: "{{ ( foreman_composite_content_views_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_composite_content_views_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_operatingsystems_redhat9_sat616: []

foreman_operatingsystems_redhat9_sat_main: []
foreman_operatingsystems_redhat9_sat: "{{ ( foreman_operatingsystems_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_operatingsystems_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_installation_media_redhat9_sat616: []

foreman_installation_media_redhat9_sat_main: []
foreman_installation_media_redhat9_sat: "{{ ( foreman_installation_media_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_installation_media_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to use a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el9: &foreman_activation_keys_defaults_el9
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 9

foreman_activation_keys_redhat9_sat616: []

foreman_activation_keys_redhat9_sat616_content_overrides:
  - label: satellite-6.16-for-rhel-9-x86_64-rpms
    override: default

foreman_activation_keys_redhat9_sat616_capsule_content_overrides:
  - label: satellite-capsule-6.16-for-rhel-9-x86_64-rpms
    override: default

foreman_activation_keys_redhat9_sat_main_content_overrides:
  - label: rhel-9-for-x86_64-baseos-rpms
    override: default
  - label: rhel-9-for-x86_64-appstream-rpms
    override: default
  - label: rhel-9-for-x86_64-supplementary-rpms
    override: default

foreman_activation_keys_redhat9_sat_main:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel9_satellite"
    organization: "{{ foreman_organization_redhat9_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9_satellite"
    <<: *foreman_activation_keys_defaults_el9
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite"
    content_overrides: "{{ ( foreman_activation_keys_redhat9_sat_main_content_overrides | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
      union( foreman_activation_keys_redhat9_sat616_content_overrides | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
    }}"

  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel9_capsule"
    organization: "{{ foreman_organization_redhat9_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel9_capsule"
    <<: *foreman_activation_keys_defaults_el9
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite"
    content_overrides: "{{ ( foreman_activation_keys_redhat9_sat_main_content_overrides | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
      union( foreman_activation_keys_redhat9_sat616_capsule_content_overrides | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
    }}"

foreman_activation_keys_redhat9_sat: "{{ ( foreman_activation_keys_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_activation_keys_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"


foreman_sync_plan_products_redhat9_sat616:
  - Red Hat Enterprise Linux for x86_64
  - Red Hat Satellite
  - Red Hat Satellite Capsule

foreman_sync_plan_products_redhat9_sat_main: []
foreman_sync_plan_products_redhat9_sat: "{{ ( foreman_sync_plan_products_redhat9_sat_main | default([]) if foreman_enable_redhat9_sat | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat611 | default([]) if foreman_enable_redhat9_sat611 | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat612 | default([]) if foreman_enable_redhat9_sat612 | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat613 | default([]) if foreman_enable_redhat9_sat613 | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat614 | default([]) if foreman_enable_redhat9_sat614 | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat615 | default([]) if foreman_enable_redhat9_sat615 | bool else [] ) |
  union( foreman_sync_plan_products_redhat9_sat616 | default([]) if foreman_enable_redhat9_sat616 | bool else [] )
  }}"

