---
# noqa: var-naming[no-role-prefix]

foreman_content_credentials_redhat8_sat: []

foreman_products_redhat8_sat:
  - name: Red Hat Satellite
    organization: "{{ foreman_organization_redhat8_sat }}"
    repository_sets:
      # Red Hat Satellite 6.11 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.11 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.11-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"
      # Red Hat Satellite 6.12 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.12 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.12-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"
      # Red Hat Satellite 6.13 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite 6.13 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-6.13-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"

  - name: Red Hat Satellite Capsule
    organization: "{{ foreman_organization_redhat8_sat }}"
    repository_sets:
      # Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.11-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"
      # Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.12-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"
      # Red Hat Satellite Capsule 6.13 for RHEL 8 x86_64 RPMs
      - name: Red Hat Satellite Capsule 6.13 for RHEL 8 x86_64 (RPMs)
        # basearch: x86_64
        # label: satellite-capsule-6.13-for-rhel-8-x86_64-rpms
        organization: "{{ foreman_organization_redhat8_sat }}"

foreman_content_views_redhat8_sat:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_611"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite 6.11 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_612"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite 6.12 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_613"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite 6.13 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"

  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_611"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite Capsule 6.11 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite Capsule'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_612"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite Capsule 6.12 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite Capsule'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_613"
    organization: "{{ foreman_organization_redhat8_sat }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Red Hat Satellite Capsule 6.13 for RHEL 8 x86_64 RPMs"
        product: "{{ foreman_product_name_prefix | default('') }}'Red Hat Satellite Capsule'"
    allow_promote: "{{ foreman_cv_allow_promote_redhat8_sat }}"

foreman_composite_content_views_redhat8_sat:
  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel8_satellite"
    organization: "{{ foreman_organization_redhat8_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat8_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat8_sat }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_ansible_2"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_ansible_29"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_611"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_612"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_613"
        latest: true

  - name: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel8_capsule"
    organization: "{{ foreman_organization_redhat8_sat }}"
    composite: True
    allow_promote: "{{ foreman_ccv_allow_promote_redhat8_sat }}"
    auto_publish: "{{ foreman_ccv_auto_publish_redhat8_sat }}"
    components:
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_baseos"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_appstream"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_supplementary"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_ansible_2"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_ansible_29"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_611"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_612"
        latest: true
      - content_view: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}rhel8_satellite_capsule_613"
        latest: true

foreman_operatingsystems_redhat8_sat: []

foreman_installation_media_redhat8_sat: []

# Refer to https://access.redhat.com/solutions/125873 for pool ids
foreman_activation_keys_defaults: &foreman_activation_keys_defaults
  # lifecycle_environment: "Library"
  # subscriptions:
  #   # Example to use a pool id
  #   # - pool_id: "8a88e9826db22df5016dd018abdd029b"
  #   # - name: "Red Hat Ansible Engine"
  #   # - name: "Red Hat Ansible Automation Platform"
  #   # - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Red Hat Enterprise Linux Server"
  #   # - name: "Red Hat Satellite"
  #   # - name: "Red Hat Satellite Capsule"
  #   # - name: "Red Hat Software Collections (for RHEL Server)"
  #   # - name: "Red Hat OpenShift Container Platform"
  #   - name: "Extra Packages for Enterprise Linux"
  #   # - name: "Foreman"
  auto_attach: False
  release_version: 7Server
  # service_level: Standard

foreman_activation_keys_defaults_el8: &foreman_activation_keys_defaults_el8
  <<: *foreman_activation_keys_defaults
  # subscriptions:
  #   - name: "Red Hat Ansible Engine"
  #   - name: "Red Hat Enterprise Linux for x86_64"
  #   - name: "Extra Packages for Enterprise Linux"
  release_version: 8

foreman_activation_keys_redhat8_sat:
  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel8_satellite"
    organization: "{{ foreman_organization_redhat8_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel8_satellite"
    <<: *foreman_activation_keys_defaults_el8
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite"
    content_overrides:
      - label: rhel-8-for-x86_64-baseos-rpms
        override: default
      - label: rhel-8-for-x86_64-appstream-rpms
        override: default
      - label: rhel-8-for-x86_64-supplementary-rpms
        override: default
      - label: ansible-2-for-rhel-8-x86_64-rpms
        override: default
      - label: ansible-2.9-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.11-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.12-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-6.13-for-rhel-8-x86_64-rpms
        override: default

  - name: "{{ foreman_ak_prefix | default('ak_') }}{{ foreman_ak_name_prefix | default('') }}rhel8_capsule"
    organization: "{{ foreman_organization_redhat8_sat }}"
    content_view: "{{ foreman_ccv_prefix | default('ccv_') }}{{ foreman_ccv_name_prefix | default('') }}rhel8_capsule"
    <<: *foreman_activation_keys_defaults_el8
    # subscriptions:
    #   - name: "Red Hat Ansible Engine"
    #   - name: "Red Hat Enterprise Linux for x86_64"
    #   - name: "Red Hat Satellite Capsule"
    content_overrides:
      - label: rhel-8-for-x86_64-baseos-rpms
        override: default
      - label: rhel-8-for-x86_64-appstream-rpms
        override: default
      - label: rhel-8-for-x86_64-supplementary-rpms
        override: default
      - label: ansible-2-for-rhel-8-x86_64-rpms
        override: default
      - label: ansible-2.9-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.11-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.12-for-rhel-8-x86_64-rpms
        override: default
      - label: satellite-capsule-6.13-for-rhel-8-x86_64-rpms
        override: default

foreman_sync_plan_products_redhat8_sat:
  - Red Hat Ansible Engine
  - Red Hat Enterprise Linux for x86_64
  - Red Hat Satellite
  - Red Hat Satellite Capsule

